DataSync: Added error code, method, property and Enum
ibm-openbmc/phosphor-dbus-interfaces pull request #160
Opened 2024-12-13 05:10 UTC by harsh-agarwal1

- Introduced the "SiblingNotAvailable" error code specific to 
DataSync interfaces.
- Introduced the "FullSync" method interface to initiate a full 
sync of the configured files and directory to the sibling BMC.
- Introduced the "SyncStatus" property and Enum to define the 
Synchronization status of the BMC.

2024-12-20 13:01 UTC, RameshIyyar requested changes

2025-01-06 04:21 UTC, RameshIyyar commented
As discussed, I am waiting for upstream approval of the changes, as the DBus interface directory has been updated based on the community's suggestion.

This PR needs to incorporate those changes, and I noticed that a few comments have not been addressed yet.

2025-01-22 04:55 UTC, closed without merging

2025-01-22 08:53 UTC, harsh-agarwal1 commented on yaml/xyz/openbmc_project/DataSync/BMCData.interface.yaml
> +          - xyz.openbmc_project.DataSync.BMCData.Error.SiblingNotAvailable
would prefer with error handling logic

2025-01-22 08:55 UTC, harsh-agarwal1 commented on yaml/xyz/openbmc_project/DataSync/BMCData.interface.yaml
> +          Start a full Sync of all the configured files and directory, to
1. Addressed
2. Can be added with future commits.

2025-01-22 08:56 UTC, harsh-agarwal1 commented
Created gerrit commits: [patch1](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/77378), [patch2](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/77379), [patch3](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/77380).