Addition of PSPD KW.
ibm-openbmc/phosphor-dbus-interfaces pull request #65
Opened 2022-11-17 06:33 UTC by GiridhariKrishnan

VPD data for Backplane.

2022-11-17 07:21 UTC, SunnySrivastava1984 requested changes
Please write a commit message explaining why this has been added and what it will hold.

2023-02-20 09:40 UTC, jinuthomas requested changes

2023-02-20 14:11 UTC, jinuthomas requested changes

2023-02-20 14:47 UTC, GiridhariKrishnan commented on gen/com/ibm/ipzvpd/meson.build
> +    'com/ibm/ipzvpd/PSPD__cpp'.underscorify(),
I'm checking and will confirm the changes.

2023-02-20 15:59 UTC, geissonator commented
add to approvelist

2023-02-20 16:01 UTC, geissonator commented
Please provide link to upstream gerrit (put out in https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/yaml/com/ibm/ipzvpd)

2023-02-20 19:16 UTC, merged