Create Validate interface for inband code update
ibm-openbmc/phosphor-dbus-interfaces pull request #73
Opened 2023-04-18 03:50 UTC by sagisin

This method will allow for validation to occur during inband code updates. It will ensure that the User Access Key, Signature, and Minimum Ship Level requirements are met before the update proceeds.

2023-04-18 18:45 UTC, geissonator commented
add to approvelist

2023-04-19 20:28 UTC, anoo1 commented
CI error seems like a network issue, retriggering.

```
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/kinetic/InRelease  Cannot initiate the connection to ports.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable
```

2023-04-19 20:28 UTC, anoo1 commented
jenkins run tests please

2023-04-20 15:50 UTC, anoo1 requested changes
Also add your name to the commit msg, and you can remove Zami as author since this has changed so much since her initial attempt for these changes.

2023-04-21 06:08 UTC, sagisin commented on yaml/xyz/openbmc_project/Software/LID.errors.yaml
done

2023-04-21 06:08 UTC, sagisin commented on gen/xyz/openbmc_project/Software/LID/meson.build
> +    command: [
done

2023-04-21 06:08 UTC, sagisin commented on gen/xyz/openbmc_project/Software/meson.build
> +    command: [
done

2023-04-21 06:09 UTC, sagisin commented on yaml/xyz/openbmc_project/Software/LID.interface.yaml
> +    An interface to validate marker LID before starting inband code update.
done

2023-04-21 06:09 UTC, sagisin commented on yaml/xyz/openbmc_project/Software/LID.interface.yaml
> +          Validate file in staging directory given the lid value 7.
done

2023-04-24 15:30 UTC, anoo1 approved these changes

2023-04-26 15:34 UTC, merged